services:
  server:
    image: spiceroll/spiceroll:latest
    build:
      context: .
      args:
        - VITE_CMS_TOKEN=${VITE_CMS_TOKEN}
        - VITE_CMS_URL=${VITE_CMS_URL}
    environment:
      - NODE_ENV=production
      - VITE_CMS_TOKEN=${VITE_CMS_TOKEN}
      - VITE_CMS_URL=${VITE_CMS_URL}
    ports:
      - 3000:3000
