name: Deploy to Docker Hub and Server

on:
    pull_request:
      branches: [main, test-deployment]
    push:
        branches:
            -main

jobs: 
    build-and-deploy:
        runs-on: ubuntu-latest

        env: 
          VITE_CMS_TOKEN: ${{ secrets.VITE_CMS_TOKEN }}
          VITE_CMS_URL: ${{ secrets.VITE_CMS_URL }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spiceRoll:latest
            
            - name: Deploy with Docker Compose
              uses: appleboy/ssh-action@v1.1.0
              with: 
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USER }}
                key: ${{ secrets.SERVER_SHH_KEY }}
                script: | 
                  docker-compose pull 
                  docker-compose up -d
