name: Deploy to Docker Hub and Server

on:
  pull_request:
    branches: [main, test-deployment]
  push:
    branches:
      - main

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            VITE_CMS_TOKEN=${{ secrets.VITE_CMS_TOKEN }}
            VITE_CMS_URL=${{ secrets.VITE_CMS_URL }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spiceroll:latest
      
      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        env:
          VITE_CMS_TOKEN: ${{ secrets.VITE_CMS_TOKEN }}
          VITE_CMS_URL: ${{ secrets.VITE_CMS_URL }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SHH_KEY }}
          envs: VITE_CMS_TOKEN,VITE_CMS_URL
          script: | 
            cd /Users/tszpak/git/spiceroll
            docker-compose pull 
            docker-compose up -d
